"""Verify src/main/resources/com/pathlocked/monsters.json against the OSRS Wiki.

For every monster in the hand-authored resource, we check three things:

  1. **Name** resolves to a wiki monster infobox (catches typos / renamed NPCs).
  2. **Combat level** — our representative ``combatLevel`` appears among the
     combat levels the wiki records for that name (monsters often have several
     variants; we accept a match against any of them, matching the plugin's
     own "kill points use the live NPC's combat level" note).
  3. **Free-to-play status** — the name is in ``Category:Free-to-play monsters``.
     Pathlocked is a F2P gamemode, so a members-only monster is a data bug.

Output: a Markdown diff report at scripts/out/monsters-report.md. This script
NEVER edits the resource JSON — another lane owns content data this stage.

Usage:
    python3 scripts/verify_monsters.py [--refresh] [--no-cache]
"""

from __future__ import annotations

import argparse
import json
import os

from wikiclient import WikiClient, WikiQueryError

REPOSITORY_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MONSTERS_JSON_PATH = os.path.join(
    REPOSITORY_ROOT, "src", "main", "resources", "com", "pathlocked", "monsters.json"
)
OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "out", "monsters-report.md")


def escape_apostrophes(value: str) -> str:
    """Escape single quotes for embedding a name inside a Bucket Lua string."""
    return value.replace("'", "\\'")


def wiki_combat_levels_for(client: WikiClient, monster_name: str) -> list:
    """Return the sorted set of combat levels the wiki records for ``monster_name``.

    Tries the name as-authored, then with a capitalised first letter (wiki page
    titles capitalise the first character). Returns an empty list if the name
    resolves to no monster infobox at all.
    """
    for candidate_name in _name_candidates(monster_name):
        statement = (
            "bucket('infobox_monster')"
            ".select('combat_level')"
            f".where('name','{escape_apostrophes(candidate_name)}')"
            ".limit(100).run()"
        )
        rows = client.bucket_query(statement)
        levels = sorted({row["combat_level"] for row in rows if row.get("combat_level") is not None})
        if rows:
            return levels
    return []


def _name_candidates(name: str) -> list:
    candidates = [name]
    capitalised = name[:1].upper() + name[1:]
    if capitalised != name:
        candidates.append(capitalised)
    return candidates


def build_report(client: WikiClient) -> str:
    with open(MONSTERS_JSON_PATH, "r", encoding="utf-8") as monsters_file:
        monsters = json.load(monsters_file)["monsters"]

    free_to_play_monsters = {title.lower() for title in client.category_members("Free-to-play monsters")}
    members_only_monsters = {title.lower() for title in client.category_members("Members' monsters")}

    rows = []
    counts = {"not_found": 0, "combat_mismatch": 0, "not_f2p": 0, "f2p_unconfirmed": 0, "ok": 0}

    for monster in monsters:
        name = monster["name"]
        our_combat_level = monster.get("combatLevel")
        wiki_levels = wiki_combat_levels_for(client, name)

        flags = []
        if not wiki_levels:
            flags.append("⚠️ name not found on wiki")
            counts["not_found"] += 1
        elif our_combat_level not in wiki_levels:
            flags.append(f"⚠️ combat level {our_combat_level} not among wiki levels")
            counts["combat_mismatch"] += 1

        lowered_names = {n.lower() for n in _name_candidates(name)}
        is_free_to_play = bool(lowered_names & free_to_play_monsters)
        is_members_only = bool(lowered_names & members_only_monsters)
        if not is_free_to_play and is_members_only:
            flags.append("⚠️ members-only on wiki (F2P gamemode!)")
            counts["not_f2p"] += 1
        elif not is_free_to_play and not is_members_only:
            flags.append("ℹ️ F2P status unconfirmed (not in either category)")
            counts["f2p_unconfirmed"] += 1

        if not flags:
            counts["ok"] += 1

        f2p_display = "yes" if is_free_to_play else ("members" if is_members_only else "?")
        wiki_levels_display = ", ".join(str(level) for level in wiki_levels) or "—"
        rows.append(
            (
                name,
                str(our_combat_level),
                wiki_levels_display,
                f2p_display,
                "; ".join(flags) if flags else "✅ ok",
            )
        )

    return render_markdown(rows, counts, len(monsters), client)


def render_markdown(rows, counts, total, client) -> str:
    lines = []
    lines.append("# monsters.json — wiki verification report")
    lines.append("")
    lines.append(
        "_Generated by `scripts/verify_monsters.py`. Read-only: this report never "
        "edits the resource JSON. Combat level matches if our value appears among "
        "the wiki's recorded levels for that name (variants included)._"
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Monsters checked: **{total}**")
    lines.append(f"- ✅ Clean: **{counts['ok']}**")
    lines.append(f"- ⚠️ Name not found: **{counts['not_found']}**")
    lines.append(f"- ⚠️ Combat-level mismatch: **{counts['combat_mismatch']}**")
    lines.append(f"- ⚠️ Members-only (should be F2P): **{counts['not_f2p']}**")
    lines.append(f"- ℹ️ F2P status unconfirmed: **{counts['f2p_unconfirmed']}**")
    lines.append("")
    lines.append(f"_Fetch: {client.stats_line()}._")
    lines.append("")
    lines.append("## Details")
    lines.append("")
    lines.append("| Monster | Our CB | Wiki CB(s) | F2P | Findings |")
    lines.append("| --- | --- | --- | --- | --- |")
    for name, our_cb, wiki_cbs, f2p, findings in rows:
        lines.append(f"| {name} | {our_cb} | {wiki_cbs} | {f2p} | {findings} |")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true", help="ignore cached responses and refetch")
    parser.add_argument("--no-cache", action="store_true", help="do not read or write the disk cache")
    arguments = parser.parse_args()

    client = WikiClient(use_cache=not arguments.no_cache, refresh=arguments.refresh)
    print(f"Verifying {MONSTERS_JSON_PATH} against the OSRS Wiki...")
    try:
        report = build_report(client)
    except WikiQueryError as error:
        raise SystemExit(f"Wiki query failed: {error}")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as report_file:
        report_file.write(report)
    print(f"Wrote {OUTPUT_PATH} ({client.stats_line()}).")


if __name__ == "__main__":
    main()
